#!/usr/bin/env bash

set -euo pipefail

PROJ_PATH="roles/"
PROJ_PREFIXES="$(find "${PROJ_PATH%/}" -type d -depth 1)"

PROJ_REPO_NAME_PATTERN="ansible-role-"'${PROJ_NAME}'
PROJ_REPO_URL_PATTERN="git@github.com:pinkeen/"'${PROJ_REPO_NAME}'".git"
PROJ_REPO_BRANCH="master"

git() {
    local RC=0; command git "$@" 1>cmdout.tmp 2>cmderr.tmp | sed 's/^/ < [OUT] /g' || RC=$?

    if (( $RC == 0 )) ; then
        echo " [OK] git $@"
        sed 's/^/ <out> /g' cmdout.tmp
    else
        echo " [FAILED] [$RC] git $@"
        sed 's/^/ <err> /g' cmderr.tmp
    fi

    rm -f cmderr.tmp cmdout.tmp
    echo
    return $RC
}

echo $PROJ_PREFIXES

for PROJ_PREFIX in $PROJ_PREFIXES ; do
    PROJ_PREFIX="${PROJ_PREFIX%/}"
    PROJ_NAME="$(basename "$PROJ_PREFIX")"
    PROJ_BRANCH="subtree-$PROJ_NAME"
    PROJ_REMOTE="subrepo-$PROJ_NAME"
    PROJ_REPO_NAME="$(eval "echo $PROJ_REPO_NAME_PATTERN")"
    PROJ_REPO_URL="$(eval "echo $PROJ_REPO_URL_PATTERN")"

    echo -e "\n *** Splitting role: $PROJ_NAME ***\n"
    echo " Git Prefix: $PROJ_PREFIX"
    echo " Git Local Branch: $PROJ_BRANCH"
    echo " Git Remote: $PROJ_REMOTE/$PROJ_BRANCH"
    echo " Git Remote URL: $PROJ_REPO_URL"
    echo " Remote Repository Name: $PROJ_REPO_NAME"
    echo " Remote Repository Branch: $PROJ_REPO_BRANCH"

    git remote add "$PROJ_REMOTE" "$PROJ_REPO_URL" \
        || git remote set-url "$PROJ_REMOTE" "$PROJ_REPO_URL"

    git subtree split "--prefix=$PROJ_PREFIX" -b "$PROJ_BRANCH"

    git push --force --set-upstream "$PROJ_REMOTE" "$PROJ_REPO_BRANCH"
    # git push --tags --set-upstream "$PROJ_REMOTE" "$PROJ_REPO_BRANCH"
done

