dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: molecule/default/lint.yml

platforms:
  - name: instance
    image: centos:7
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra

  lint:
    name: flake8
